# dev baseURL is http://127.0.0.1:5500
# gh-pages is https://francoiducat.github.io/yeulocation.ducatillon.net
# hugo server --baseURL http://localhost:1313
baseURL: https://yeulocation.ducatillon.net
languageCode: fr-fr
title: Yeu Location
params:
  homeHeaderImage: /img/tyler-lastovich-eWD2G26XytQ-unsplash.jpg
  author:
    name: François
    siteUrl: https://notes.ducatillon.net/
  scripts:
    bootstrap: |
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    lightbox: |
      <script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>

menu:
  main:
  - name: Nos Maisons
    url: /maisons
    weight: 70
    params:
      target: 
  - name: Gallerie
    url: /photos
    weight: 80
    params:
      target: 
  - name: FAQ
    url: /faq
    weight: 90
    params:
      target: 
  footer:
  - name: Nos Maisons
    url: /maisons
    weight: 80
    params:
      target: 
  - name: FAQ
    url: /faq
    weight: 90
    params:
      target: 

 