baseURL: https://yeulocation.ducatillon.net
languageCode: fr-fr
title: Yeu Location
theme: air
params:
  author:
    name: François
    siteUrl: https://notes.ducatillon.net/
  gmaps_url: https://www.google.com/maps/d/u/0/embed?mid=1z1myaoqFSxQHFXoC9iPxTkcwOXo&ehbc=2E312F
  mainColor: "#035c8c"
  footer: "Réservez en direct au +33 (0)6 09 62 99 08"
  scripts:
    bootstrap: |
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" async></script>
    imageloaded: |
      <script src="https://cdnjs.cloudflare.com/ajax/libs/imagesloaded/4.1.4/imagesloaded.pkgd.min.js" async></script>
    masonry: |
     <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
    lightbox: |
      <script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js" async></script>
menu:
  main:
  - name: Nos Maisons
    url: /maisons
    weight: 70
    params:
      target: 
  - name: Gallerie
    url: /photos
    weight: 80
    params:
      target: 
  - name: FAQ
    url: /faq
    weight: 90
    params:
      target: 
  footer:
  - name: Nos Maisons
    url: /maisons
    weight: 80
    params:
      target: 
  - name: FAQ
    url: /faq
    weight: 90
    params:
      target: 

markup:
  goldmark:
    renderer:
      unsafe: true
